# Generated by Django 3.0.3 on 2020-03-04 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('board_id', models.CharField(max_length=1024, primary_key=True, serialize=False)),
                ('board_title', models.CharField(max_length=100)),
                ('board_content', models.TextField()),
                ('file_name', models.CharField(max_length=200)),
                ('board_dtm', models.DateTimeField()),
            ],
        ),
    ]
