# Generated by Django 3.0.3 on 2020-03-04 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='file_name',
        ),
    ]
